input_dir: Sources/WonderAppView
output_dir: ${TARGET_TEMP_DIR}

strings:
  inputs:
    - Support/en.lproj
  outputs:
    - templatePath: .swiftgen.l10n.stencil
      output: Strings+Generated.swift

xcassets:
  inputs:
    - Support/Assets.xcassets
  outputs:
    - templatePath: .swiftgen.assets.stencil
      output: Assets+Generated.swift
